{
 "title": "dashboard2",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Go gc_duration_milliseconds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(go_gc_duration_seconds_sum{job=\"blog_service\"}[1m])) /  sum by (job)(rate(go_gc_duration_seconds_count{job=\"blog_service\"}[1m])) * 1000"
    }
   ]
  },
  {
   "title": "Go Allocated Memory in MB",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"blog_service\"} / 1024 / 1024"
    }
   ]
  },
  {
   "title": "Go Mem Total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=\"blog_service\"}[1m])"
    }
   ]
  },
  {
   "title": "Go Goroutines",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"blog_service\"}"
    }
   ]
  },
  {
   "title": "HTTP request duration Success",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job=\"blog_service\", code =~ \"2..\"}[5m])) by (job, le))",
     "legendFormat": "95pecentile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_request_duration_seconds_bucket{job=\"blog_service\", code =~ \"2..\"}[5m])) by (job, le))",
     "legendFormat": "90pecentile"
    }
   ]
  },
  {
   "title": "HTTP request duration Success by endpoints",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job=\"blog_service\", code =~ \"2..\", handler = \"/v1/posts\"}[5m])) by (job, method, handler, le))"
    }
   ]
  },
  {
   "title": "HTTP request duration Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job=\"blog_service\", code =~ \"5..\"}[5m])) by (job, le))\n",
     "legendFormat": "95percentile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_request_duration_seconds_bucket{job=\"blog_service\", code =~ \"5..\"}[5m])) by (job, le))\n",
     "legendFormat": "90percentile"
    }
   ]
  },
  {
   "title": "HTTP request Error rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{job=\"blog_service\", code =~ \"5..\"}[5m])) by (job, le)  / sum(rate(http_request_duration_seconds_count{job=\"blog_service\"}[5m])) by (job, le)"
    }
   ]
  },
  {
   "title": "HTTP QPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (increase(http_api_requests_total{job=\"blog_service\"}[5m])) by (job, handler, method)"
    },
    {
     "expr": "sum (increase(http_api_requests_total{job=\"blog_service\"}[5m])) by (job)",
     "legendFormat": "total"
    }
   ]
  }
 ]
}