{
 "title": "my dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "HTTP request duration failed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(request_duration_seconds_bucket[5m])) by (job, code, le))"
    }
   ]
  },
  {
   "title": "HTTP request duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(request_duration_seconds_bucket[5m])) by (job, le))\n\n"
    }
   ]
  },
  {
   "title": "Go Allocated Memory in MB",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"blog_service\"} / 1024 / 1024"
    }
   ]
  },
  {
   "title": "HTTP requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(api_requests_total{job=\"blog_service\"}[1m])"
    }
   ]
  }
 ]
}